=== brightmarch/orderware/src/Orderware/AppBundle/Resources/public/schemas/inventory_v1.schema.json
{
    "id": "https://orderware.io/bundles/orderwareapp/schemas/inventory_v1.request.json",
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "division": {
            "type": "string"
        },
        "quantity_type": {
            "enum": ["full", "incr"]
        },
        "facilities": {
            "type": "array",
            "minItems": 0,
            "items": {
                "type": "object",
                "properties": {
                    "facility_code": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "address1": {
                        "type": ["string", "null"]
                    },
                    "address2": {
                        "type": ["string", "null"]
                    },
                    "city_name": {
                        "type": ["string", "null"]
                    },
                    "postal_code": {
                        "type": ["string", "null"]
                    },
                    "state_code": {
                        "type": ["string", "null"]
                    },
                    "state_name": {
                        "type": ["string", "null"]
                    },
                    "country_code": {
                        "type": ["string", "null"]
                    },
                    "country_name": {
                        "type": ["string", "null"]
                    },
                    "longitude": {
                        "type": ["string", "number", "null"]
                    },
                    "latitude": {
                        "type": ["string", "number", "null"]
                    },
                    "units_per_day": {
                        "type": "integer",
                        "minimum": 0
                    },
                    "master": {
                        "type": "boolean"
                    }
                },
                "additionalProperties": false,
                "required": [
                    "facility_code",
                    "name",
                    "address1",
                    "address2",
                    "city_name",
                    "postal_code",
                    "state_code",
                    "state_name",
                    "country_code",
                    "country_name",
                    "longitude",
                    "latitude",
                    "units_per_day",
                    "master"
                ]
            }
        },
        "skus": {
            "type": "array",
            "minItems": 0,
            "items": {
                "properties": {
                    "skucode": {
                        "type": "string"
                    },
                    "facility_code": {
                        "type": "string"
                    },
                    "quantity": {
                        "type": "integer"
                    }
                },
                "additionalProperties": false,
                "required": [
                    "skucode",
                    "facility_code",
                    "quantity"
                ]
            }
        }
    },
    "additionalProperties": false,
    "required": [
        "division",
        "quantity_type",
        "facilities",
        "skus"
    ]
}

=== brightmarch/orderware/src/Orderware/AppBundle/Resources/public/schemas/inventory_v1.json
{
    "division": "GROWERS",
    "quantity_type": "full",
    "facilities": [
        {
            "facility_code": "GROWERS01",
            "name": "Growers Coffee - Dallas, TX",
            "address1": "1000 Place Road",
            "address2": null,
            "city_name": "Dallas",
            "postal_code": "75228",
            "state_code": "TX",
            "state_name": "Texas",
            "country_code": "US",
            "country_name": "United States",
            "longitude": "0.0",
            "latitude": "0.0",
            "units_per_day": 9999,
            "master": true
        },
        {
            "facility_code": "GROWERS02",
            "name": "Growers Coffee - Pataskala, OH",
            "address1": "999 Shipment Place",
            "address2": "Suite #1445",
            "city_name": "Pataskala",
            "postal_code": "69930",
            "state_code": "OH",
            "state_name": "Ohio",
            "country_code": "US",
            "country_name": "United States",
            "longitude": "0.0",
            "latitude": "0.0",
            "units_per_day": 99999,
            "master": false
        }
    ],
    "skus": [
        {
            "skucode": "G100001B",
            "facility_code": "GROWERS01",
            "quantity": 10
        },
        {
            "skucode": "G100001B",
            "facility_code": "GROWERS02",
            "quantity": 33
        }
    ]
}
